services:
  - type: web
    name: api-plugin-speech
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    runtime: python
    branch: main
    autoDeploy: true