services:
  - type: web
    name: wp-audio-articles-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import pyttsx3; print('TTS OK')"
    startCommand: |
      python main.py
    envVars:
      - key: WP_AUDIO_API_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: MAX_CACHE_SIZE
        value: "20"
      - key: MAX_TEXT_LENGTH
        value: "5000"
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: wp-audio-cache
      mountPath: /tmp
      sizeGB: 1